# Generated by Django 6.0.4 on 2026-05-02 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reklame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_reklame', models.CharField(max_length=100, unique=True)),
                ('nama_pemilik', models.CharField(max_length=255)),
                ('nik_npwp', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('luas_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tinggi_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status_reklame', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_pasang', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reklame',
            },
        ),
        migrations.CreateModel(
            name='ReklameKategori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
                ('ukuran_max', models.CharField(blank=True, max_length=100, null=True)),
                ('retribusi_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'reklame_kategori',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_profil', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ZonaTataRuang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_zona', models.CharField(max_length=255)),
                ('tipe_zona', models.CharField(max_length=100)),
                ('geometri_geojson', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona_tata_ruang',
            },
        ),
        migrations.CreateModel(
            name='FotoReklame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='foto/reklame/')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reklame', models.ForeignKey(db_column='reklame_id', on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='aset.reklame')),
            ],
            options={
                'db_table': 'foto_reklame',
            },
        ),
        migrations.CreateModel(
            name='DokumenReklame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_dokumen', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_file', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(upload_to='dokumen/reklame/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reklame', models.ForeignKey(db_column='reklame_id', on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='aset.reklame')),
            ],
            options={
                'db_table': 'perizinan_dokumen',
            },
        ),
        migrations.AddField(
            model_name='reklame',
            name='kategori',
            field=models.ForeignKey(blank=True, db_column='kategori_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aset.reklamekategori'),
        ),
        migrations.CreateModel(
            name='Perizinan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_registrasi', models.CharField(max_length=100, unique=True)),
                ('status_perizinan', models.CharField(default='PENDING', max_length=50)),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('tanggal_keputusan', models.DateField(blank=True, null=True)),
                ('catatan_keputusan', models.TextField(blank=True, null=True)),
                ('masa_berlaku', models.DateField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('reklame', models.ForeignKey(db_column='reklame_id', on_delete=django.db.models.deletion.CASCADE, to='aset.reklame')),
                ('pemohon', models.ForeignKey(db_column='pemohon_id', on_delete=django.db.models.deletion.CASCADE, related_name='perizinan_pemohon', to='aset.users')),
            ],
            options={
                'db_table': 'perizinan',
            },
        ),
        migrations.AddField(
            model_name='reklame',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='zona_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aset.zonatataruang'),
        ),
    ]
