# Generated by Django 6.0.4 on 2026-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklame',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reklame',
            name='kuasa_pengguna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reklame',
            name='pengguna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
