# Generated by Django 6.0.4 on 2026-07-11 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0002_add_kabupaten_pengguna_kuasa_to_reklame'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanMasyarakat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pelapor', models.CharField(blank=True, max_length=255, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pelapor', models.EmailField(blank=True, max_length=254, null=True)),
                ('isi_laporan', models.TextField()),
                ('kategori_laporan', models.CharField(choices=[('REKLAME_ILEGAL', 'Reklame Ilegal'), ('REKLAME_RUSAK', 'Reklame Rusak'), ('MELANGGAR_ZONA', 'Melanggar Zona'), ('REKLAME_KADALUARSA', 'Reklame Kadaluarsa'), ('LAINNYA', 'Lainnya')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/laporan/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('alamat_lokasi', models.CharField(blank=True, max_length=500, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_laporan', models.CharField(choices=[('PENDING', 'Pending'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='PENDING', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reklame', models.ForeignKey(blank=True, db_column='reklame_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan', to='aset.reklame')),
            ],
            options={
                'db_table': 'laporan_masyarakat',
                'ordering': ['-created_at'],
            },
        ),
    ]
